on:
  push:
    branches:
      - "main"
      


jobs:
  merge-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'test'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
  open-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    if: failure()
    steps:
      - uses: peter-evans/create-pull-request@v4
          
